/* Generated By:JavaCC: Do not edit this line. PandasCategoricalParserConstants.java */
package org.jpmml.lightgbm;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface PandasCategoricalParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LBRACKET = 2;
  /** RegularExpression Id. */
  int RBRACKET = 3;
  /** RegularExpression Id. */
  int COMMA = 4;
  /** RegularExpression Id. */
  int FALSE = 5;
  /** RegularExpression Id. */
  int NULL = 6;
  /** RegularExpression Id. */
  int TRUE = 7;
  /** RegularExpression Id. */
  int INT = 8;
  /** RegularExpression Id. */
  int FLOAT = 9;
  /** RegularExpression Id. */
  int STRING = 10;
  /** RegularExpression Id. */
  int SIGN = 11;
  /** RegularExpression Id. */
  int DIGIT = 12;
  /** RegularExpression Id. */
  int EXPONENT = 13;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"[\"",
    "\"]\"",
    "\",\"",
    "\"false\"",
    "\"null\"",
    "\"true\"",
    "<INT>",
    "<FLOAT>",
    "<STRING>",
    "<SIGN>",
    "<DIGIT>",
    "<EXPONENT>",
    "\"pandas_categorical:\"",
  };

}
